
CREATE TABLE S_USER_ACTIVITY (
  `ID` VARCHAR(36) NOT NULL,
  `USER_ID` BIGINT(20) NOT NULL,
  `ACTIVITY_DATE` TIMESTAMP NOT NULL,
  `TYPE` VARCHAR(128) NOT NULL,
  `DATA` TEXT NULL,
  PRIMARY KEY (`ID`));

ALTER TABLE S_USER_ACTIVITY ADD INDEX `FK_USER_ACTIVITY_USER_IDX` (`USER_ID` ASC);

ALTER TABLE S_USER_ACTIVITY 
ADD CONSTRAINT `FK_USER_ACTIVITY_USER`
  FOREIGN KEY (`USER_ID`)
  REFERENCES S_USER (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

CREATE TABLE S_USER_SESSION (
  `SESSION` VARCHAR(36) NOT NULL,
  `USER_ID` BIGINT(20) NOT NULL,
  `CREATED` TIMESTAMP NOT NULL,
  `LAST_ACCESS` TIMESTAMP,	
  `EXPIRATION` TIMESTAMP,	
  PRIMARY KEY (`SESSION`));

ALTER TABLE S_USER_SESSION ADD INDEX `FK_USER_SESSION_USER_IDX` (`USER_ID` ASC);

ALTER TABLE S_USER_SESSION
ADD CONSTRAINT `FK_USER_SESSION_USER`
  FOREIGN KEY (`USER_ID`)
  REFERENCES S_USER (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
ALTER TABLE B_BILLING_MODEL 
ADD COLUMN `VAT_LIQUIDATION_TYPE` VARCHAR(32) NULL AFTER `STORE_PRICE_PER_LOCATION`,
ADD COLUMN `RECEIVER_ID` BIGINT(20) NULL AFTER `VAT_LIQUIDATION_TYPE`;

ALTER TABLE B_BILLING_MODEL ADD INDEX `B_BILLING_MODEL_RECEIVER_IDX` (`RECEIVER_ID` ASC);

ALTER TABLE B_BILLING_MODEL 
ADD CONSTRAINT `B_BILLING_MODEL_RECEIVER`
  FOREIGN KEY (`RECEIVER_ID`)
  REFERENCES B_LEGAL_ENTITY (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
ALTER TABLE B_BILL_DETAIL ADD INDEX `INDEX_BILL_TYPE` (`DTYPE` ASC, `BILL_ID` ASC);

ALTER TABLE B_LIQUIDATION_DETAIL ADD INDEX `INDEX_LIQUIDATION_DETAIL` (`LIQUIDATION_ID` ASC);

ALTER TABLE B_LIQUIDATION_DETAIL ADD COLUMN `LIQUIDATION_INCLUDED` BIT NOT NULL DEFAULT TRUE AFTER `LIQUIDATION_ID`;

ALTER TABLE B_BILL_DETAIL ADD COLUMN `LIQUIDATION_INCLUDED` BIT NOT NULL DEFAULT TRUE AFTER `BILL_ID`;

ALTER TABLE B_BILL
ADD COLUMN `LIQUIDATION_MANUAL_AMOUNT` DECIMAL(18,2) NULL AFTER `LIQUIDATION_TOTAL_AMOUNT`,
ADD COLUMN `LIQUIDATION_OUTER_AMOUNT` DECIMAL(18,2) NULL AFTER `LIQUIDATION_MANUAL_AMOUNT`;

UPDATE B_BILL SET LIQUIDATION_MANUAL_AMOUNT = ADJUSTMENT_AMOUNT;

ALTER TABLE B_BILL DROP COLUMN `ADJUSTMENT_AMOUNT`;

ALTER TABLE B_BILL_DETAIL 
ADD COLUMN `NET_VALUE` DECIMAL(18,2) NULL AFTER `LIQUIDATION_INCLUDED`,
ADD COLUMN `VAT_VALUE` DECIMAL(18,2) NULL AFTER `NET_VALUE`,
ADD COLUMN `VAT_PERCENT` DECIMAL(18,2) NULL AFTER `VAT_VALUE`;

UPDATE B_BILLING_MODEL SET VAT_LIQUIDATION_TYPE = 'EXCLUDED';

ALTER TABLE B_BILL
ADD COLUMN `LIQUIDATION_TOTAL_VAT` DECIMAL(18,2) NULL DEFAULT NULL AFTER `LIQUIDATION_PRICE_PER_LOCATION`,
ADD COLUMN `LIQUIDATION_TOTAL_NET_AMOUNT` DECIMAL(18,2) NULL DEFAULT NULL AFTER `LIQUIDATION_TOTAL_VAT`;

ALTER TABLE B_BILL_DETAIL 
CHANGE COLUMN `BASE_VALUE` `SOURCE_VALUE` DECIMAL(18,2) NULL DEFAULT NULL;

ALTER TABLE B_LIQUIDATION_DETAIL 
ADD COLUMN `SOURCE_VALUE` DECIMAL(18,2) NULL DEFAULT NULL AFTER `LIQUIDATION_INCLUDED`,
ADD COLUMN `NET_VALUE` DECIMAL(18,2) NULL DEFAULT NULL AFTER `SOURCE_VALUE`,
ADD COLUMN `VAT_VALUE` DECIMAL(18,2) NULL DEFAULT NULL AFTER `NET_VALUE`;

ALTER TABLE B_LIQUIDATION 
ADD COLUMN `NET_AMOUNT` DECIMAL(18,2) NULL DEFAULT NULL AFTER `REPORT_FILE_ID`,
ADD COLUMN `VAT_AMOUNT` DECIMAL(18,2) NULL DEFAULT NULL AFTER `NET_AMOUNT`,
ADD COLUMN `TOTAL_AMOUNT` DECIMAL(18,2) NULL DEFAULT NULL AFTER `VAT_AMOUNT`;

UPDATE B_BILL_DETAIL SET LIQUIDATION_INCLUDED = true WHERE LIQUIDATION_INCLUDED = null;

ALTER TABLE B_LIQUIDATION
ADD COLUMN `STORE_MANUAL_OUTER_AMOUNT` DECIMAL(18,2) NULL DEFAULT NULL AFTER `TOTAL_AMOUNT`;

ALTER TABLE B_LIQUIDATION 
ADD COLUMN `TOTAL_OUTER_AMOUNT` DECIMAL(18,2) NULL DEFAULT NULL AFTER `STORE_MANUAL_OUTER_AMOUNT`;

ALTER TABLE B_LIQUIDATION 
ADD COLUMN `LIQUIDATION_EFFECTIVE_AMOUNT` DECIMAL(18,2) NULL DEFAULT NULL AFTER `TOTAL_OUTER_AMOUNT`;

UPDATE B_BILL_DETAIL SET NET_VALUE = VALUE WHERE NET_VALUE IS NULL;
UPDATE B_BILL_DETAIL SET VAT_VALUE = 0 WHERE VAT_VALUE IS NULL;

UPDATE B_BILL_DETAIL SET CONCEPT_TYPE = 'STAKES' WHERE CONCEPT_TYPE = 'Stakes';
UPDATE B_BILL_DETAIL SET CONCEPT_TYPE = 'SAT_MONTHLY_FEES' WHERE CONCEPT_TYPE = 'SatMonthlyFees';
UPDATE B_BILL_DETAIL SET CONCEPT_TYPE = 'COMMERCIAL_MONTHLY_FEES' WHERE CONCEPT_TYPE = 'CommercialMonthlyFees';
UPDATE B_BILL_DETAIL SET CONCEPT_TYPE = 'PRICE_PER_LOCATION' WHERE CONCEPT_TYPE = 'PricePerLocation';
UPDATE B_BILL_DETAIL SET CONCEPT_TYPE = 'MANUAL_WITH_LIQUIDATION' WHERE CONCEPT_TYPE = 'ManualWithLiquidation';
UPDATE B_BILL_DETAIL SET CONCEPT_TYPE = 'MANUAL_WITHOUT_LIQUIDATION' WHERE CONCEPT_TYPE = 'ManualWithoutLiquidation';

UPDATE B_BILL_RAW_DATA SET CONCEPT = 'NR' WHERE CONCEPT = '0';
UPDATE B_BILL_RAW_DATA SET CONCEPT = 'NGR' WHERE CONCEPT = '1';
UPDATE B_BILL_RAW_DATA SET CONCEPT = 'GGR' WHERE CONCEPT = '2';
UPDATE B_BILL_RAW_DATA SET CONCEPT = 'STAKES' WHERE CONCEPT = '3';
UPDATE B_BILL_RAW_DATA SET CONCEPT = 'BONUS' WHERE CONCEPT = '4'; -- 0 rows
UPDATE B_BILL_RAW_DATA SET CONCEPT = 'COMMERCIAL_MONTHLY_FEES' WHERE CONCEPT = '5'; -- 0 rows
UPDATE B_BILL_RAW_DATA SET CONCEPT = 'COOPERATING_MONTHLY_FEES' WHERE CONCEPT = '6'; -- 0 rows
UPDATE B_BILL_RAW_DATA SET CONCEPT = 'SAT_MONTLY_FEES' WHERE CONCEPT = '7'; -- 0 rows
UPDATE B_BILL_RAW_DATA SET CONCEPT = 'PRICE_PER_LOCATION' WHERE CONCEPT = '8';
UPDATE B_BILL_RAW_DATA SET CONCEPT = 'STORE_CASH' WHERE CONCEPT = '9';
UPDATE B_BILL_RAW_DATA SET CONCEPT = 'CREDIT' WHERE CONCEPT = '10';
UPDATE B_BILL_RAW_DATA SET CONCEPT = 'MANUAL' WHERE CONCEPT = '11';
UPDATE B_BILL_RAW_DATA SET CONCEPT = 'ADJUSTMENT' WHERE CONCEPT = '12';
UPDATE B_BILL_RAW_DATA SET CONCEPT = 'MANUAL_WITH_LIQUIDATION' WHERE CONCEPT = '13';
UPDATE B_BILL_RAW_DATA SET CONCEPT = 'MANUAL_WITHOUT_LIQUIDATION' WHERE CONCEPT = '14';
UPDATE B_BILL_RAW_DATA SET CONCEPT = 'OTHER' WHERE CONCEPT = '15';
UPDATE B_BILL_RAW_DATA SET CONCEPT = 'TOTAL_BET_AMOUNT' WHERE CONCEPT = '16';
UPDATE B_BILL_RAW_DATA SET CONCEPT = 'CANCELLED' WHERE CONCEPT = '17';
UPDATE B_BILL_RAW_DATA SET CONCEPT = 'TOTAL_WIN_AMOUNT' WHERE CONCEPT = '18';
UPDATE B_BILL_RAW_DATA SET CONCEPT = 'TOTAL_ATTRIBUTABLE' WHERE CONCEPT = '19';
UPDATE B_BILL_RAW_DATA SET CONCEPT = 'MARGIN' WHERE CONCEPT = '20';