
CREATE TABLE S_USER_ACTIVITY (
  `ID` VARCHAR(36) NOT NULL,
  `USER_ID` BIGINT(20) NOT NULL,
  `ACTIVITY_DATE` TIMESTAMP NOT NULL,
  `TYPE` VARCHAR(128) NOT NULL,
  `DATA` TEXT NULL,
  PRIMARY KEY (`ID`));

ALTER TABLE S_USER_ACTIVITY ADD INDEX `FK_USER_ACTIVITY_USER_IDX` (`USER_ID` ASC);

ALTER TABLE S_USER_ACTIVITY 
ADD CONSTRAINT `FK_USER_ACTIVITY_USER`
  FOREIGN KEY (`USER_ID`)
  REFERENCES S_USER (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

CREATE TABLE S_USER_SESSION (
  `SESSION` VARCHAR(36) NOT NULL,
  `USER_ID` BIGINT(20) NOT NULL,
  `CREATED` TIMESTAMP NOT NULL,
  `LAST_ACCESS` TIMESTAMP,	
  `EXPIRATION` TIMESTAMP,	
  PRIMARY KEY (`SESSION`));

ALTER TABLE S_USER_SESSION ADD INDEX `FK_USER_SESSION_USER_IDX` (`USER_ID` ASC);

ALTER TABLE S_USER_SESSION
ADD CONSTRAINT `FK_USER_SESSION_USER`
  FOREIGN KEY (`USER_ID`)
  REFERENCES S_USER (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;